-- ============================================================
-- Nudgeable Action Engine — combined schema migration
-- Auto-generated by concatenating supabase/migrations/001..021 in order.
-- Run this ONCE against a fresh Supabase project (SQL Editor: New query -> paste -> Run).
-- Do not run against a database that already has some of these migrations applied —
-- use the individual files in supabase/migrations/ for incremental upgrades instead.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;

-- ------------------------------------------------------------
-- Source: supabase/migrations/001_base_schema.sql
-- ------------------------------------------------------------
-- Nudgeable Action Engine: Base schema (Phase 0) – multi-tenant
-- Run in Supabase SQL Editor or via supabase db push

-- 1. Companies first (profiles and actions reference them)
CREATE TABLE IF NOT EXISTS public.companies (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Profiles (extends Supabase Auth); company_id and role for multi-tenant
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  company_id UUID REFERENCES public.companies(id) ON DELETE SET NULL,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin', 'superadmin')),
  -- For user roles, league_index stores league index: 0=Starter,1=Bronze,2=Silver,3=Gold,4=Diamond
  league_index INTEGER DEFAULT 0,
  weekly_goal INTEGER DEFAULT 3,
  total_points INTEGER DEFAULT 0,
  streak INTEGER DEFAULT 0,
  last_active_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Action Library (company-scoped)
CREATE TYPE action_theme AS ENUM ('Collaboration', 'Feedback', 'Accountability', 'Connection', 'Coaching');

CREATE TABLE IF NOT EXISTS public.actions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  created_by UUID REFERENCES public.profiles(id),
  theme action_theme NOT NULL,
  title TEXT NOT NULL,
  how TEXT NOT NULL,
  why TEXT NOT NULL,
  points INTEGER DEFAULT 5,
  time_estimate TEXT DEFAULT '5 mins',
  is_system_action BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. User Actions (behavioral ledger)
CREATE TYPE action_status AS ENUM ('scheduled', 'success', 'failed', 'skipped', 'habit_started', 'cemented');

CREATE TABLE IF NOT EXISTS public.user_actions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action_id UUID REFERENCES public.actions(id) ON DELETE CASCADE NOT NULL,
  status action_status DEFAULT 'scheduled',
  scheduled_at TIMESTAMPTZ,
  completed_reps INTEGER DEFAULT 0,
  reps_remaining INTEGER,
  reflection TEXT,
  is_calendar_synced BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, action_id)
);

-- 5. Social Feed Events
CREATE TYPE event_type AS ENUM ('ACCEPTED', 'SUCCESS', 'HABIT_STARTED', 'CEMENTED', 'DECLINED');

CREATE TABLE IF NOT EXISTS public.feed_events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action_title TEXT NOT NULL,
  type event_type NOT NULL,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime for feed
ALTER PUBLICATION supabase_realtime ADD TABLE public.feed_events;

-- RLS: enable on all tables
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feed_events ENABLE ROW LEVEL SECURITY;

-- Companies: superadmin full access; company admin and user read own company
CREATE POLICY "Superadmin full companies" ON public.companies
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
  );
CREATE POLICY "Read own company" ON public.companies
  FOR SELECT USING (
    id IN (SELECT company_id FROM public.profiles WHERE id = auth.uid() AND company_id IS NOT NULL)
  );

-- Profiles: read/update own; superadmin can update any; company admin can read profiles in their company
CREATE POLICY "Users read own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Superadmin update any profile" ON public.profiles
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'superadmin')
  );
CREATE POLICY "Company admin read company profiles" ON public.profiles
  FOR SELECT USING (
    company_id IS NOT NULL
    AND company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'superadmin') LIMIT 1)
  );
CREATE POLICY "Service or trigger insert profile" ON public.profiles FOR INSERT WITH CHECK (true);

-- Actions: read where action.company_id = user's company_id; insert/update/delete by company admin for that company or superadmin
CREATE POLICY "Read actions in my company" ON public.actions
  FOR SELECT USING (
    company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1)
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
  );
CREATE POLICY "Company admin or superadmin insert actions" ON public.actions
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (
      p.role = 'superadmin'
      OR (p.role = 'admin' AND p.company_id = company_id)
    ))
  );
CREATE POLICY "Company admin or superadmin update actions" ON public.actions
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (
      p.role = 'superadmin'
      OR (p.role = 'admin' AND p.company_id = actions.company_id)
    ))
  );
CREATE POLICY "Company admin or superadmin delete actions" ON public.actions
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (
      p.role = 'superadmin'
      OR (p.role = 'admin' AND p.company_id = actions.company_id)
    ))
  );

-- User actions: CRUD own
CREATE POLICY "Users CRUD own user_actions" ON public.user_actions FOR ALL USING (auth.uid() = user_id);

-- Feed events: read all (filter by company in app); insert own
CREATE POLICY "Anyone read feed_events" ON public.feed_events FOR SELECT USING (true);
CREATE POLICY "Users insert own feed_events" ON public.feed_events FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Trigger: create profile on signup (company_id null, role 'user')
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, company_id, role)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url',
    NULL,
    'user'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ------------------------------------------------------------
-- Source: supabase/migrations/002_seed_actions.sql
-- ------------------------------------------------------------
-- Seed: one company (Demo Company) + Action Library for that company (Phase 0)
-- From lib/constants.ts ACTION_DECK. Run after 001_base_schema.sql.

-- 1. Insert one company (id will be used for actions)
INSERT INTO public.companies (name, slug)
VALUES ('Demo Company', 'demo-company')
ON CONFLICT (slug) DO NOTHING;

-- 2. Seed actions for Demo Company (company_id from slug); skip if already present
INSERT INTO public.actions (company_id, theme, title, how, why, points, time_estimate, is_system_action)
SELECT c.id, a.theme, a.title, a.how, a.why, a.points, a.time_estimate, true
FROM public.companies c,
LATERAL (VALUES
  ('Accountability'::action_theme, 'End your next meeting by summarizing key takeaways and explicitly asking if anything was unclear', 'In the last 2 minutes, state: "Here is what I heard as our core decisions... does anyone have a different understanding or feels something is missing?"', 'Ambiguity is the enemy of action. Explicit summaries prevent misalignment and wasted effort.', 5, '5 mins'),
  ('Collaboration', 'Recognize and reward teams that achieve creative solutions or innovations through collaboration.', 'Send a quick shoutout in your shared channel specifically highlighting HOW two people or teams worked together to solve a complex problem.', 'What gets measured gets managed; what gets celebrated gets repeated.', 5, '2 mins'),
  ('Feedback', 'Ask for a "1% Improvement" Tip at the end of a project sync', 'Ask: "What is one thing we could do 1% better in our next sprint to make your life easier?"', 'Small continuous adjustments are more sustainable than large-scale overhauls.', 5, '3 mins'),
  ('Connection', 'Set time to connect with family or friends', 'Block 30 minutes in your personal calendar this week specifically for a call or visit with someone you haven''t spoken to in over a month.', 'Social health directly impacts professional cognitive endurance.', 5, '30 mins'),
  ('Coaching', 'Connect your team member with a mentor in your network', 'Identify one growth area for a direct report and introduce them via email to someone in your network who excels in that area.', 'Expanding a team''s network is the highest leverage coaching action a leader can take.', 5, '10 mins'),
  ('Collaboration', 'In your next project meeting, clearly define and document each team member''s roles and responsibilities.', 'Create a simple RACI matrix or bulleted list during the call and share it immediately after.', 'Role clarity reduces friction and prevents duplicated effort.', 5, '15 mins')
) AS a(theme, title, how, why, points, time_estimate)
WHERE c.slug = 'demo-company'
  AND NOT EXISTS (SELECT 1 FROM public.actions ac WHERE ac.company_id = c.id AND ac.title = a.title);

-- ------------------------------------------------------------
-- Source: supabase/migrations/003_optional_test_roles.sql
-- ------------------------------------------------------------
-- Optional: Promote existing users to superadmin or company admin for testing.
-- Run the commands below in Supabase SQL Editor after you have created users via sign-up.
-- Replace YOUR_USER_UUID with the actual id from auth.users (or profiles).
--
-- Promote one user to superadmin (no company):
--   UPDATE public.profiles SET role = 'superadmin', company_id = NULL WHERE id = 'YOUR_USER_UUID';
--
-- Promote one user to company admin for Demo Company:
--   UPDATE public.profiles SET role = 'admin', company_id = (SELECT id FROM public.companies WHERE slug = 'demo-company' LIMIT 1) WHERE id = 'YOUR_USER_UUID';
--
-- Assign a regular user to Demo Company (so they see the Action Library):
--   UPDATE public.profiles SET company_id = (SELECT id FROM public.companies WHERE slug = 'demo-company' LIMIT 1) WHERE id = 'YOUR_USER_UUID';

-- No-op so this migration runs successfully
SELECT 1;

-- ------------------------------------------------------------
-- Source: supabase/migrations/004_seed_superadmin.sql
-- ------------------------------------------------------------
-- Seed a superadmin user (admin@actionengine / admin@actionengine)
-- This creates the user directly in auth.users and profiles.
-- Password is hashed using crypt function.

-- 1. Insert into auth.users (Supabase Auth)
-- Note: This uses a fixed UUID for idempotency. If the user already exists, it will be skipped.
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
)
VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a0000000-0000-0000-0000-000000000001', -- fixed UUID for superadmin
  'authenticated',
  'authenticated',
  'admin@actionengine',
  crypt('admin@actionengine', gen_salt('bf')), -- bcrypt hash of password
  NOW(), -- email already confirmed
  NOW(),
  NOW(),
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Superadmin"}',
  NOW(),
  NOW(),
  '',
  '',
  '',
  ''
)
ON CONFLICT (id) DO NOTHING;

-- 1b. Insert into auth.identities (REQUIRED for email login to work)
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
)
VALUES (
  'a0000000-0000-0000-0000-000000000001',
  'a0000000-0000-0000-0000-000000000001',
  '{"sub": "a0000000-0000-0000-0000-000000000001", "email": "admin@actionengine"}'::jsonb,
  'email',
  'a0000000-0000-0000-0000-000000000001',
  NOW(),
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;

-- 2. Insert into profiles (superadmin role, no company)
INSERT INTO public.profiles (
  id,
  full_name,
  avatar_url,
  company_id,
  role,
  league_index,
  weekly_goal,
  total_points,
  streak,
  last_active_at,
  created_at
)
VALUES (
  'a0000000-0000-0000-0000-000000000001', -- same UUID as auth.users
  'Superadmin',
  NULL,
  NULL, -- superadmin has no company
  'superadmin',
  0,
  3,
  0,
  0,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  role = 'superadmin',
  company_id = NULL,
  full_name = 'Superadmin';

-- Note: You can now log in with:
-- Email: admin@actionengine
-- Password: admin@actionengine

-- ------------------------------------------------------------
-- Source: supabase/migrations/005_fix_superadmin_identity.sql
-- ------------------------------------------------------------
-- Fix: Add missing auth.identities record for superadmin (required for login)
-- Run this if you seeded 004 but cannot log in with admin@actionengine.
-- Creates the identity record so Supabase Auth can verify the password.

INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  'a0000000-0000-0000-0000-000000000001',
  'a0000000-0000-0000-0000-000000000001',
  '{"sub": "a0000000-0000-0000-0000-000000000001", "email": "admin@actionengine"}'::jsonb,
  'email',
  'a0000000-0000-0000-0000-000000000001',
  NOW(),
  NOW(),
  NOW()
WHERE EXISTS (SELECT 1 FROM auth.users WHERE id = 'a0000000-0000-0000-0000-000000000001')
  AND NOT EXISTS (SELECT 1 FROM auth.identities WHERE user_id = 'a0000000-0000-0000-0000-000000000001' AND provider = 'email');

-- ------------------------------------------------------------
-- Source: supabase/migrations/006_packages.sql
-- ------------------------------------------------------------
-- Phase 2a: Packages (company-scoped)
-- packages, package_actions, package_assignments

CREATE TABLE IF NOT EXISTS public.packages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  created_by UUID REFERENCES public.profiles(id),
  name TEXT NOT NULL,
  description TEXT,
  skill_theme TEXT,
  start_date DATE,
  duration_weeks INTEGER DEFAULT 8,
  actions_per_week INTEGER DEFAULT 2,
  delivery_time TIME,
  rule_of_five INTEGER DEFAULT 5,
  points_weight INTEGER DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.package_actions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  package_id UUID NOT NULL REFERENCES public.packages(id) ON DELETE CASCADE,
  action_id UUID NOT NULL REFERENCES public.actions(id) ON DELETE CASCADE,
  week_number INTEGER,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(package_id, action_id)
);

CREATE TABLE IF NOT EXISTS public.package_assignments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  package_id UUID NOT NULL REFERENCES public.packages(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  scheduled_start_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(package_id, user_id)
);

ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_assignments ENABLE ROW LEVEL SECURITY;

-- Packages: company admin of that company or superadmin
CREATE POLICY "Read packages in my company" ON public.packages
  FOR SELECT USING (
    company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1)
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
  );
CREATE POLICY "Admin insert packages" ON public.packages
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (
      p.role = 'superadmin'
      OR (p.role = 'admin' AND p.company_id = company_id)
    ))
  );
CREATE POLICY "Admin update packages" ON public.packages
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (
      p.role = 'superadmin'
      OR (p.role = 'admin' AND p.company_id = packages.company_id)
    ))
  );
CREATE POLICY "Admin delete packages" ON public.packages
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (
      p.role = 'superadmin'
      OR (p.role = 'admin' AND p.company_id = packages.company_id)
    ))
  );

-- Package actions: same as package access
CREATE POLICY "Read package_actions" ON public.package_actions
  FOR SELECT USING (
    package_id IN (SELECT id FROM public.packages WHERE company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1))
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
  );
CREATE POLICY "Admin insert package_actions" ON public.package_actions
  FOR INSERT WITH CHECK (
    package_id IN (
      SELECT p.id FROM public.packages p
      JOIN public.profiles pr ON pr.id = auth.uid() AND (pr.role = 'superadmin' OR (pr.role = 'admin' AND pr.company_id = p.company_id))
    )
  );
CREATE POLICY "Admin update delete package_actions" ON public.package_actions
  FOR UPDATE USING (
    package_id IN (
      SELECT p.id FROM public.packages p
      JOIN public.profiles pr ON pr.id = auth.uid() AND (pr.role = 'superadmin' OR (pr.role = 'admin' AND pr.company_id = p.company_id))
    )
  );
CREATE POLICY "Admin delete package_actions" ON public.package_actions
  FOR DELETE USING (
    package_id IN (
      SELECT p.id FROM public.packages p
      JOIN public.profiles pr ON pr.id = auth.uid() AND (pr.role = 'superadmin' OR (pr.role = 'admin' AND pr.company_id = p.company_id))
    )
  );

-- Package assignments: same
CREATE POLICY "Read package_assignments" ON public.package_assignments
  FOR SELECT USING (
    package_id IN (SELECT id FROM public.packages WHERE company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1))
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
  );
CREATE POLICY "Admin insert package_assignments" ON public.package_assignments
  FOR INSERT WITH CHECK (
    package_id IN (
      SELECT p.id FROM public.packages p
      JOIN public.profiles pr ON pr.id = auth.uid() AND (pr.role = 'superadmin' OR (pr.role = 'admin' AND pr.company_id = p.company_id))
    )
  );
CREATE POLICY "Admin update package_assignments" ON public.package_assignments
  FOR UPDATE USING (
    package_id IN (
      SELECT p.id FROM public.packages p
      JOIN public.profiles pr ON pr.id = auth.uid() AND (pr.role = 'superadmin' OR (pr.role = 'admin' AND pr.company_id = p.company_id))
    )
  );
CREATE POLICY "Admin delete package_assignments" ON public.package_assignments
  FOR DELETE USING (
    package_id IN (
      SELECT p.id FROM public.packages p
      JOIN public.profiles pr ON pr.id = auth.uid() AND (pr.role = 'superadmin' OR (pr.role = 'admin' AND pr.company_id = p.company_id))
    )
  );

-- ------------------------------------------------------------
-- Source: supabase/migrations/007_admin_user_actions.sql
-- ------------------------------------------------------------
-- Phase 2a: Allow company admins to create user_actions for users in their company
-- (needed for Deploy & Enrol - package assignment)

CREATE POLICY "Admin insert user_actions for company users" ON public.user_actions
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.role = 'superadmin')
    OR user_id IN (
      SELECT p.id FROM public.profiles p
      WHERE p.company_id = (SELECT pr.company_id FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.role = 'admin' LIMIT 1)
    )
  );

CREATE POLICY "Admin update user_actions for company users" ON public.user_actions
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.role = 'superadmin')
    OR user_id IN (
      SELECT p.id FROM public.profiles p
      WHERE p.company_id = (SELECT pr.company_id FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.role = 'admin' LIMIT 1)
    )
  );

-- ------------------------------------------------------------
-- Source: supabase/migrations/008_profiles_policy_recursion_fix.sql
-- ------------------------------------------------------------
-- Fix: infinite recursion in profiles RLS policies.
-- Policies that SELECT from profiles while evaluating access to profiles cause recursion.
-- Use SECURITY DEFINER functions so role/company_id are read without triggering RLS.

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_user_company_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;

-- Replace policies that query profiles (causing recursion) with function-based checks
DROP POLICY IF EXISTS "Superadmin update any profile" ON public.profiles;
CREATE POLICY "Superadmin update any profile" ON public.profiles
  FOR UPDATE USING (public.current_user_role() = 'superadmin');

DROP POLICY IF EXISTS "Company admin read company profiles" ON public.profiles;
CREATE POLICY "Company admin read company profiles" ON public.profiles
  FOR SELECT USING (
    company_id IS NOT NULL
    AND company_id = public.current_user_company_id()
    AND public.current_user_role() IN ('admin', 'superadmin')
  );

-- ------------------------------------------------------------
-- Source: supabase/migrations/009_user_actions_accepted_at.sql
-- ------------------------------------------------------------
-- Add accepted_at to user_actions: when user committed (with or without a specific schedule).
-- - When user picks date/time: scheduled_at = that time, accepted_at = now().
-- - When user "accepts" without time (do whenever): scheduled_at = null, accepted_at = now().
-- Validation queue shows "Scheduled for xyz" vs "Accepted on xyz" using these.

ALTER TABLE public.user_actions
  ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;

COMMENT ON COLUMN public.user_actions.accepted_at IS 'When the user committed to this action (plan or accept without schedule).';

-- ------------------------------------------------------------
-- Source: supabase/migrations/010_package_actions_delivery_date.sql
-- ------------------------------------------------------------
-- Add per-action (per-week) delivery dates for packages
-- This lets admins control exactly when each week's delivery goes live.

ALTER TABLE public.package_actions
ADD COLUMN IF NOT EXISTS delivery_date DATE;


-- ------------------------------------------------------------
-- Source: supabase/migrations/011_package_actions_delivery_time.sql
-- ------------------------------------------------------------
-- Add per-action (per-delivery) time of day for packages
-- This lets each delivery within a package have its own delivery_time.

ALTER TABLE public.package_actions
ADD COLUMN IF NOT EXISTS delivery_time TIME;


-- ------------------------------------------------------------
-- Source: supabase/migrations/012_habit_occurrences.sql
-- ------------------------------------------------------------
-- Habit loop: store committed rep dates (daily sprint = next 4 days; weekly = same weekday next 4 weeks).
-- Used to show "scheduled for Feb 10" etc. in the queue and to drive reminders.

CREATE TABLE IF NOT EXISTS public.habit_occurrences (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action_id UUID REFERENCES public.actions(id) ON DELETE CASCADE NOT NULL,
  user_action_id UUID REFERENCES public.user_actions(id) ON DELETE CASCADE NOT NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_habit_occurrences_user_action
  ON public.habit_occurrences(user_action_id);
CREATE INDEX IF NOT EXISTS idx_habit_occurrences_user_scheduled
  ON public.habit_occurrences(user_id, scheduled_at);

ALTER TABLE public.habit_occurrences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users CRUD own habit_occurrences" ON public.habit_occurrences
  FOR ALL USING (auth.uid() = user_id);

COMMENT ON TABLE public.habit_occurrences IS 'Committed rep dates for habit loop (Rule of 5). Daily = next 4 days; Weekly = same weekday next 4 weeks.';

-- ------------------------------------------------------------
-- Source: supabase/migrations/013_auto_login_infrastructure.sql
-- ------------------------------------------------------------
-- Auto-login infrastructure: persistent keys + logging
-- NO email sending; internal preparation only.

-- 1. Add persistent_login_key to profiles
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS persistent_login_key UUID UNIQUE;

-- 2. Create index for fast key lookups
CREATE INDEX IF NOT EXISTS idx_profiles_persistent_login_key
  ON public.profiles(persistent_login_key)
  WHERE persistent_login_key IS NOT NULL;

-- 3. Create auto_login_logs table for security audit
CREATE TABLE IF NOT EXISTS public.auto_login_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ip_address TEXT,
  user_agent TEXT,
  success BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auto_login_logs_user_id
  ON public.auto_login_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_auto_login_logs_created_at
  ON public.auto_login_logs(created_at DESC);

-- RLS: service role only (no direct client access)
ALTER TABLE public.auto_login_logs ENABLE ROW LEVEL SECURITY;

-- No SELECT policy for anon/authenticated - only service role can read/write
CREATE POLICY "Service role only auto_login_logs" ON public.auto_login_logs
  FOR ALL USING (false) WITH CHECK (false);

COMMENT ON TABLE public.auto_login_logs IS 'Audit log for auto-login attempts. Accessible only via service role.';
COMMENT ON COLUMN public.profiles.persistent_login_key IS 'UUID used for persistent auto-login links. Rotate via admin when needed.';

-- ------------------------------------------------------------
-- Source: supabase/migrations/014_auto_login_backfill_and_trigger.sql
-- ------------------------------------------------------------
-- Backfill persistent_login_key for existing users
-- and update trigger so new users get a key automatically

-- 1. Backfill: create profiles for any auth.users that don't have one (edge case)
INSERT INTO public.profiles (id, persistent_login_key)
SELECT id, gen_random_uuid()
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 2. Backfill: assign key to all existing profiles that don't have one
UPDATE public.profiles
SET persistent_login_key = gen_random_uuid()
WHERE persistent_login_key IS NULL;

-- 3. Update handle_new_user to set persistent_login_key for new signups
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, company_id, role, persistent_login_key)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url',
    NULL,
    'user',
    gen_random_uuid()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ------------------------------------------------------------
-- Source: supabase/migrations/015_email_campaign_logs.sql
-- ------------------------------------------------------------
-- Email campaign logs: track every login email sent
-- Prevents duplicate sends, provides audit trail

CREATE TABLE IF NOT EXISTS public.email_campaign_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  email TEXT NOT NULL,
  template_id TEXT,
  status TEXT NOT NULL DEFAULT 'sent',
  error_message TEXT,
  sent_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_campaign_logs_user_id
  ON public.email_campaign_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_email_campaign_logs_created_at
  ON public.email_campaign_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_campaign_logs_user_date
  ON public.email_campaign_logs(user_id, created_at DESC);

ALTER TABLE public.email_campaign_logs ENABLE ROW LEVEL SECURITY;

-- Only service role can access (no direct client access)
CREATE POLICY "Service role only email_campaign_logs" ON public.email_campaign_logs
  FOR ALL USING (false) WITH CHECK (false);

COMMENT ON TABLE public.email_campaign_logs IS 'Audit log for login emails sent via SendGrid. Service role only.';

-- ------------------------------------------------------------
-- Source: supabase/migrations/016_remove_unused_package_columns.sql
-- ------------------------------------------------------------
-- Remove unused columns from packages table
-- These fields are no longer used in the UI:
-- - actions_per_week (frequency)
-- - rule_of_five (deployment enrollment setting)
-- - points_weight (deployment enrollment setting)

ALTER TABLE public.packages DROP COLUMN IF EXISTS actions_per_week;
ALTER TABLE public.packages DROP COLUMN IF EXISTS rule_of_five;
ALTER TABLE public.packages DROP COLUMN IF EXISTS points_weight;

-- ------------------------------------------------------------
-- Source: supabase/migrations/017_remove_actions_points_column.sql
-- ------------------------------------------------------------
-- Remove points column from actions table
-- XP reward strength is no longer used in action creation

ALTER TABLE public.actions DROP COLUMN IF EXISTS points;

-- ------------------------------------------------------------
-- Source: supabase/migrations/018_remove_skill_theme.sql
-- ------------------------------------------------------------
-- Remove the skill_theme column from packages; package name is the only identity field now.
ALTER TABLE public.packages DROP COLUMN IF EXISTS skill_theme;

-- ------------------------------------------------------------
-- Source: supabase/migrations/019_email_schedules.sql
-- ------------------------------------------------------------
-- Email schedules: cron-based scheduled email sending via SendGrid templates
-- The Vercel cron hits /api/cron/email-scheduler every hour;
-- this table stores what to send, to whom, and when.

CREATE TABLE IF NOT EXISTS public.email_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Display & template
  name TEXT NOT NULL,
  template_id TEXT NOT NULL,

  -- Target users (UUIDs from auth.users)
  user_ids UUID[] NOT NULL DEFAULT '{}',

  -- Schedule configuration
  -- 'daily'       → every day at run_time_utc
  -- 'weekly'      → every 7 days at run_time_utc
  -- 'every_n_days'→ every interval_days days at run_time_utc
  -- 'specific_date'→ one-time fire at specific_run_at, then deactivated
  schedule_type TEXT NOT NULL CHECK (
    schedule_type IN ('daily', 'weekly', 'every_n_days', 'specific_date')
  ),

  interval_days    INTEGER,       -- used when schedule_type = 'every_n_days'
  run_time_utc     TEXT NOT NULL DEFAULT '09:00', -- HH:MM in UTC, unused for specific_date
  specific_run_at  TIMESTAMPTZ,   -- used when schedule_type = 'specific_date'

  -- Runtime state
  next_run_at      TIMESTAMPTZ NOT NULL,
  last_run_at      TIMESTAMPTZ,
  last_run_status  TEXT,          -- 'success' | 'partial' | 'failed'
  last_run_sent    INTEGER NOT NULL DEFAULT 0,
  last_run_failed  INTEGER NOT NULL DEFAULT 0,

  is_active BOOLEAN NOT NULL DEFAULT true,

  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_schedules_next_run
  ON public.email_schedules(next_run_at, is_active);

ALTER TABLE public.email_schedules ENABLE ROW LEVEL SECURITY;

-- Only accessible via service role (admin client); no direct browser access
CREATE POLICY "Service role only email_schedules" ON public.email_schedules
  FOR ALL USING (false) WITH CHECK (false);

COMMENT ON TABLE public.email_schedules IS
  'Cron-based scheduled email sends. Vercel cron fires /api/cron/email-scheduler hourly; '
  'the handler picks up rows where next_run_at <= now() and is_active = true.';

-- ------------------------------------------------------------
-- Source: supabase/migrations/020_user_credential_delivery.sql
-- ------------------------------------------------------------
-- Staging table for welcome emails: holds auth user id + plaintext password until SendGrid sends.
-- Supabase Auth stores only a hash; this table exists solely to pass credentials to email.
-- RLS enabled with no policies → only the service role (server) can read/write.
-- Rows are retained so admins can resend credential emails from the control panel.
-- SECURITY: Plaintext passwords are sensitive; protect service role keys and database access.

CREATE TABLE IF NOT EXISTS public.user_credential_delivery (
  user_id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  plaintext_password TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.user_credential_delivery ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.user_credential_delivery IS
  'Stored login email + plaintext password for SendGrid template data. Service role only.';

-- ------------------------------------------------------------
-- Source: supabase/migrations/021_self_serve_actions.sql
-- ------------------------------------------------------------
-- Self-serve AI action generation + weekly reminder emails.
-- Replaces the Habit Loop (Rule of 5 rep-tracking) with:
--   1. Personal, AI-generated actions a user creates for themselves (actions.is_personal)
--   2. A user-picked weekly reminder cadence per accepted action (action_reminders)
--   3. A lightweight per-week "mark done" log (action_reminder_completions)
-- The habit loop's own table and per-user_action rep counters are dropped.

-- 1. Personal actions ---------------------------------------------------------

ALTER TABLE public.actions
  ADD COLUMN IF NOT EXISTS is_personal BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.actions.is_personal IS
  'True for actions a user generated/created for themselves (e.g. via AI onboarding). Visible only to their own creator, not the wider company action bank.';

DROP POLICY IF EXISTS "Read actions in my company" ON public.actions;
CREATE POLICY "Read actions in my company" ON public.actions
  FOR SELECT USING (
    (
      company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1)
      AND (is_personal = FALSE OR created_by = auth.uid())
    )
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'superadmin')
  );

CREATE POLICY "Users insert own personal actions" ON public.actions
  FOR INSERT WITH CHECK (
    is_personal = TRUE
    AND created_by = auth.uid()
    AND company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid() LIMIT 1)
  );

-- 2. Onboarding flag on profiles ----------------------------------------------

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS self_onboarding_completed_at TIMESTAMPTZ;

COMMENT ON COLUMN public.profiles.self_onboarding_completed_at IS
  'Set once the user completes the self-serve AI action onboarding wizard. NULL means the wizard should still be shown.';

-- 3. Weekly reminder subscriptions ---------------------------------------------

CREATE TABLE IF NOT EXISTS public.action_reminders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  user_action_id UUID REFERENCES public.user_actions(id) ON DELETE CASCADE NOT NULL,
  action_id UUID REFERENCES public.actions(id) ON DELETE CASCADE NOT NULL,
  times_per_week INTEGER NOT NULL CHECK (times_per_week BETWEEN 1 AND 7),
  -- Intended time of day the user plans to do the action (display copy only —
  -- the reminder email itself always sends on the daily cron's one Monday run).
  time_of_day_utc TEXT NOT NULL DEFAULT '03:30',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  next_run_at TIMESTAMPTZ NOT NULL,
  last_sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_action_id)
);

CREATE INDEX IF NOT EXISTS idx_action_reminders_next_run
  ON public.action_reminders(next_run_at, is_active);
CREATE INDEX IF NOT EXISTS idx_action_reminders_user
  ON public.action_reminders(user_id);

ALTER TABLE public.action_reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users CRUD own action_reminders" ON public.action_reminders
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.action_reminders IS
  'A user''s weekly reminder cadence for one accepted action. Cron sends one summary email per due row, grouped by user, each Monday.';

-- 4. Per-week lightweight completion log ---------------------------------------

CREATE TABLE IF NOT EXISTS public.action_reminder_completions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reminder_id UUID REFERENCES public.action_reminders(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  week_start_date DATE NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(reminder_id, week_start_date)
);

ALTER TABLE public.action_reminder_completions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users CRUD own action_reminder_completions" ON public.action_reminder_completions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.action_reminder_completions IS
  'Lightweight "I did this" mark for a reminder''s current week. No reps/cementing threshold — replaces the old habit_occurrences rep queue.';

-- 5. Remove the Habit Loop (Rule of 5) storage ----------------------------------

DROP TABLE IF EXISTS public.habit_occurrences;

ALTER TABLE public.user_actions
  DROP COLUMN IF EXISTS completed_reps,
  DROP COLUMN IF EXISTS reps_remaining;

-- Note: action_status enum values 'habit_started'/'cemented' and event_type enum
-- values 'HABIT_STARTED'/'CEMENTED' are intentionally left in place (Postgres
-- cannot cheaply drop enum values). The application no longer produces them.

COMMIT;
