-- Cron-safe Commitment Wallet summary for action-reminder emails.
--
-- get_my_commitment_wallet() and get_my_commitment_buddies() key off
-- auth.uid(), so they only work inside a user's own session. The reminder
-- email is generated by a cron job acting for many users at once, so this
-- adds a service-role-only equivalent parameterised by p_user_id: the
-- recipient's live Commitment Score, cohort team totals/rank, and (if
-- assigned) their first commitment buddy's live score. Read-only, no writes.

CREATE OR REPLACE FUNCTION public.get_commitment_wallet_email_summary(p_user_id UUID, p_cohort_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  v_plan public.commitment_wallet_plans%ROWTYPE;
  v_has_plan BOOLEAN := FALSE;
  v_current_score NUMERIC := NULL;
  v_team_maximum INTEGER := 0;
  v_team_plan_points INTEGER := 0;
  v_team_action_points INTEGER := 0;
  v_team_points INTEGER := 0;
  v_team_members INTEGER := 0;
  v_rank INTEGER := NULL;
  v_buddy_id UUID;
  v_buddy_name TEXT := NULL;
  v_buddy_plan_id UUID;
  v_buddy_score NUMERIC := NULL;
BEGIN
  SELECT * INTO v_plan
  FROM public.commitment_wallet_plans
  WHERE user_id = p_user_id AND cohort_id = p_cohort_id;
  v_has_plan := FOUND;
  IF v_has_plan THEN
    v_current_score := public.commitment_wallet_plan_score(v_plan.id);
  END IF;

  SELECT
    COALESCE(SUM(maximum_points + plan_bonus_points), 0)::INTEGER,
    COALESCE(SUM(plan_bonus_points), 0)::INTEGER,
    COUNT(*)::INTEGER
  INTO v_team_maximum, v_team_plan_points, v_team_members
  FROM public.commitment_wallet_plans
  WHERE cohort_id = p_cohort_id;

  SELECT COALESCE(SUM(points_awarded), 0)::INTEGER
  INTO v_team_action_points
  FROM public.commitment_wallet_events
  WHERE cohort_id = p_cohort_id;

  v_team_points := v_team_plan_points + v_team_action_points;

  IF v_has_plan THEN
    WITH contributions AS (
      SELECT
        plan.user_id,
        plan.plan_bonus_points + COALESCE(SUM(event.points_awarded), 0)::INTEGER AS points
      FROM public.commitment_wallet_plans AS plan
      LEFT JOIN public.commitment_wallet_events AS event ON event.plan_id = plan.id
      WHERE plan.cohort_id = p_cohort_id
      GROUP BY plan.id, plan.user_id, plan.plan_bonus_points
    ), ranked AS (
      SELECT user_id, DENSE_RANK() OVER (ORDER BY points DESC)::INTEGER AS contribution_rank
      FROM contributions
    )
    SELECT contribution_rank INTO v_rank FROM ranked WHERE user_id = p_user_id;
  END IF;

  -- First commitment buddy (by earliest pairing), if the recipient has one.
  SELECT other_member.user_id
  INTO v_buddy_id
  FROM public.commitment_buddy_members AS mine
  JOIN public.commitment_buddy_members AS other_member
    ON other_member.group_id = mine.group_id
   AND other_member.user_id <> mine.user_id
  JOIN public.cohort_members AS active_member
    ON active_member.cohort_id = other_member.cohort_id
   AND active_member.user_id = other_member.user_id
  WHERE mine.cohort_id = p_cohort_id
    AND mine.user_id = p_user_id
  ORDER BY other_member.created_at
  LIMIT 1;

  IF v_buddy_id IS NOT NULL THEN
    SELECT COALESCE(NULLIF(BTRIM(full_name), ''), 'Your buddy') INTO v_buddy_name
    FROM public.profiles WHERE id = v_buddy_id;

    SELECT id INTO v_buddy_plan_id
    FROM public.commitment_wallet_plans
    WHERE user_id = v_buddy_id AND cohort_id = p_cohort_id;

    IF v_buddy_plan_id IS NOT NULL THEN
      v_buddy_score := public.commitment_wallet_plan_score(v_buddy_plan_id);
    END IF;
  END IF;

  RETURN JSONB_BUILD_OBJECT(
    'hasFinalisedPlan', v_has_plan,
    'currentScore', v_current_score,
    'teamPoints', v_team_points,
    'teamMaximumPoints', v_team_maximum,
    'contributionRank', v_rank,
    'teamMemberCount', v_team_members,
    'buddyName', v_buddy_name,
    'buddyScore', v_buddy_score
  );
END;
$$;

REVOKE ALL ON FUNCTION public.get_commitment_wallet_email_summary(UUID, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_commitment_wallet_email_summary(UUID, UUID) TO service_role;
